apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: overture-stage
resources:
  - ../../base/overture/
  - httproute.yaml

labels:
  - pairs:
      env: staging
      app.kubernetes.io/instance: staging
    includeSelectors: false

patches:
  - target:
      kind: Namespace
      name: overture
    patch: |
      - op: replace
        path: /metadata/name
        value: overture-stage
