apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibrato
  namespace: vibrato
spec:
  template:
    spec:
      containers:
        - name: vibrato
          image: ghcr.io/gjcourt/vibrato:23ec524e82887fd032fa390678c5b2b4b45e334a
          env:
            - name: LEVA_NODE_ID
              value: "espresso"
