apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibrato
  namespace: vibrato
spec:
  template:
    spec:
      containers:
        - name: vibrato
          image: ghcr.io/gjcourt/vibrato:ae819da1dce230ec7ea08d3fe679eaf1b5be1db6
          env:
            - name: LEVA_NODE_ID
              value: "espresso"
