apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibrato
  namespace: vibrato
spec:
  template:
    spec:
      containers:
        - name: vibrato
          image: ghcr.io/gjcourt/vibrato:2e7a71e240650fcea5ddb1221b7e7d829d0c42e8
          env:
            - name: LEVA_NODE_ID
              value: "espresso"
