# AWS credentials for CNPG S3 backups
# Encrypt with SOPS before committing
apiVersion: v1
kind: Secret
metadata:
  name: linkding-aws-creds-secret
  namespace: linkding
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:tdmqSCFpYHxJcTvK/+wmo2gwpN8=,iv:Afz8HI3L0PteodL40p5H0+mmIRbAU+4w7Xy1bWo6NN0=,tag:QwBHY+E1C0lJHOgP3yLtBQ==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:w8TgP1wbECDSFzOWAOsKSaMDLpCwMtAQF/xFYc/R0I9wOfvf1V4b8g==,iv:nI3Fzi3T1k4zryq3sB6NBKHAPKxRJSGUVO2nsgh0C/A=,tag:WbE0RHakegFBqs6NvXwYbg==,type:str]
sops:
  age:
    - recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MS9jOUhQaDRVcDFQeWlv
        RTNLUEIzTUFxd2NVTHlGWnZpaFBVcU9oUzJJCjJwT2M4cXljYWltdU5IMVFVTlho
        aWcyWkVDd1hTTVdqclFDNXRIRU4wSEkKLS0tIC9FenNnZmh0R3JIWFhoSWo2RjFU
        OHpod3dyYWdpNzZDRDZOMGFwam9JamcKhAlpacDlp2S4DmCUnDMIa+GBm1/DpNJ+
        eHS10Z15oWqBjkkSrFdejCoJXLTNTOxM761LWKD2r6WG28xcQIZezA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T17:08:03Z"
  mac: ENC[AES256_GCM,data:iv2knkaicGSMx4XNgrO99idmSOq2Iq1HSiNFUSf5dYOuY68+nw6UUmiypPNUgDzNf1OTS2HXvRv09l0LisRTSO/P5120w0qpZuLpHBtDz4BjC9UJsiDGzwNCOAkrur6NIyTva6aR1DkJI4VXvg5f3iveHXwvauZFwDq5tv9YHWE=,iv:zbonbN3V7gn3z2Ooy6zYp5SEy99jW1w86XKOiZReoGc=,tag:yu44J9ThMl89afKxIX2QtQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
