apiVersion: v1
kind: Secret
metadata:
  name: linkding-oidc-secret
  namespace: linkding
type: Opaque
stringData:
  LD_OIDC_CLIENT_SECRET: "mdxYpU1siyzpaVdf0RSZw4dC4oNafG0.NaQ9JzkxB8Xsz~lcnfcd36FeCvPtAubnTb3AEgo5"