apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate@sha256:d911740e2e4ad80f2ff9c9ee081d6ad8031cc5d52929941adb0beed6c7406685

              args:
                - gjcourt/homelab
                - gjcourt/llmux
                - gjcourt/tempo-interview
                - gjcourt/drift
                - gjcourt/Pingo
                - gjcourt/golinks
                - gjcourt/vitals
                - gjcourt/soundbyte
                - gjcourt/python-nginx-signing

              envFrom:
                - configMapRef:
                    name: renovate-container-env
                - secretRef:
                    name: secret-renovate-container-env

          restartPolicy: Never
