apiVersion: v1
kind: Secret
metadata:
  name: secret-renovate-container-env
  namespace: renovate
data:
  RENOVATE_TOKEN: ENC[AES256_GCM,data:7N+9tz7xXMsYuqPX3udvIpviCr3CRhlMx3w9Q3X+pSdQwju32lO1HdnWuDtP7l6akRWC/nHVbNk=,iv:IALQSj6IzZ/tXiS3LOU9o42lDSsAQala+GMgQ5+DMpo=,tag:7vWOyYvB3hju9TVtEWvFjQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUkp6aDJWNU44YlU3KzF6
        OEdFamk0ZU55L0p0NVd5Q09BUmVyeHIzU25zCnI0NGh3NEw1NVdsNGpoNDhzWTNz
        RXIrMTAyM05MZ1F6d1NQckM2UFBMd0kKLS0tIFRZMXRMMktmeFRTSmhveFZQYTBh
        OEN2VU1raE5uOEEwcEdtZVZ6SHlyUFEKm7/+9OIdRrmQNWSrjB1Vdw952HGnXS+H
        cmz/C2Y9gO3WyTwD6WkCRXmMrBx7eigbfT02S1m5e0vLqGhy9+v0JQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-27T06:20:06Z"
  mac: ENC[AES256_GCM,data:7z3MxRzvpqx2v/opQ7kfYO+sahQnZc3VoNjnmP45Ic5CBIAk1FZzenTV0mDFj4zv3lqTOTjrtuFhdjt0XA2OAlIulk1yfhtJnxNaZ2zaPRS6ZApqsJ3iMUVwT4mLl2Q5Z7LxCaPscQDIxwtldRy1F36fxiJNg6h4Ed4apZ8iGeY=,iv:4DI3MwGU1cP9GcLy2S76zX62HZVI1KWVQF/glV76anA=,tag:ocftp3x+l0+DslfYWvrIjg==,type:str]
  version: 3.10.2
