apiVersion: v1
kind: Service
metadata:
  name: truenas-iscsi-exporter
  namespace: truenas-iscsi-monitor
  labels:
    app: truenas-iscsi-exporter
spec:
  selector:
    app: truenas-iscsi-exporter
  ports:
    - port: 8000
      targetPort: metrics
      name: metrics
