apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: truenas-iscsi-exporter
  namespace: truenas-iscsi-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: truenas-iscsi-exporter
  endpoints:
    - port: metrics
      interval: 60s
  namespaceSelector:
    matchNames:
      - truenas-iscsi-monitor
