apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibrato
  namespace: vibrato
spec:
  template:
    spec:
      containers:
        - name: vibrato
          image: ghcr.io/gjcourt/vibrato:0d42c3fb770ba7de48c5c41b7e3215beb933cd10
          env:
            - name: LEVA_NODE_ID
              value: "vibrato-stage"
