apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibrato
  namespace: vibrato
spec:
  template:
    spec:
      containers:
        - name: vibrato
          image: ghcr.io/gjcourt/vibrato:b6133b6639e29e30efc355e0ff498f0762eb4d7a
          env:
            - name: LEVA_NODE_ID
              value: "vibrato-stage"
