apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibrato
  namespace: vibrato
spec:
  template:
    spec:
      containers:
        - name: vibrato
          image: ghcr.io/gjcourt/vibrato:7fc5ac4fc67a4c72255a35af2b0d6fd825d4cd4e
          env:
            - name: LEVA_NODE_ID
              value: "vibrato-stage"
