apiVersion: v1
kind: Secret
metadata:
  name: adguard-sync-credentials
  namespace: adguard-stage
type: Opaque
stringData:
  ORIGIN_USERNAME: ENC[AES256_GCM,data:fYaxJVT5,iv:BcxHGuTEhq44ZKWKHTesFOHyKtni4nctnQV0+bNHdjs=,tag:hfJiE8yJy8PM2rY/13kDWg==,type:str]
  ORIGIN_PASSWORD: ENC[AES256_GCM,data:mxaX5/mL0BgDVHhJeBKHWeCR3A==,iv:oDCzm9EM/H/g5F756y5ABD0uBqdQMpepRpFnSoAiL9I=,tag:JWR03PystWv/ap5ZnEHAmA==,type:str]
  REPLICA1_USERNAME: ENC[AES256_GCM,data:/Z9nSNWa,iv:ijnk3G0vC80PA1rBvxab8AqExOERAcPC9sgjEw8pD30=,tag:d8G+eaLZ2fs4BLIvOT95DQ==,type:str]
  REPLICA1_PASSWORD: ENC[AES256_GCM,data:zyhQAUeAr++0TxzG78ApdBQw+g==,iv:eo9hbkIXkbz2UtrHtFaZOihe6qBS8fEBEwFJ6qPe/Yw=,tag:a/dAEkFoYP/w8p7rhS7I/A==,type:str]
sops:
  age:
    - recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZXErMHljMldid3Z4KzZV
        WkIxSzkra3dwbm45ZU5Nc3ZrKzN0cWtreEZzClA2SzlyVGFadUxic0I2QVluZDhl
        SjRXRWk2WkhuVDdUZ2w3V3lwYVdEMjAKLS0tIEtFOUJNdE9OOUEvOHhSSzV5MUZN
        NjMrQUFILzN3amtCWlhvOWpyZG4zYjAKkxFBHhzAFmshdnQndP8g6AiBsHcpviK4
        LDwgRF+9YVfKi5Midb8CwUx4h2VbNexfy4xlhJyrmW5AtJ461mbh4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T18:11:21Z"
  mac: ENC[AES256_GCM,data:hW2NUQBGmUg1PBFRS7KdXXgrrmp4Qpd29cS39tSq+DN8HHxzzgHAsUcULoPdT4YtZrdI/aOJOQJJe+WiwXnPMTJT2e8P8Z2UvD/U52Gp1W6Kj82kscX4SxhG2YomoMHA56OZGfoq0G4ZQWolGQdkV8A7lvRWo6dco/TYkiK2x74=,iv:dMn2QLliHWZxWLY/y+LJj2h9Z626xUhwS0tsuNPwTjM=,tag:b1fammvL1c1O/bHCu4GjBw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
