#ENC[AES256_GCM,data:mzYWkCO8CUCkx4nMr5Wy/Bp8bajkiqWaQN50tujKrqstnVHiCNfZS+EfUix1/PMG2L6l3Y93jhNEeSA7S0f/uVpexaV/NxpZcKak,iv:EUymmqmbmuyF7zbv4pqHjIFqJBQz6QIO3GiFKX7k+SA=,tag:nYvy9rRtUQFhnX1PWko+YA==,type:comment]
#ENC[AES256_GCM,data:N8ICOJecsQyjAHwS5v+lsd1Hw5h73uHiubvliEPIMbiLw2DdayknzhNiydZiFOmsJv9fjzl/gIbRTkbwvITs,iv:KY8ErRHxc730EEIxM+Zho1Wz1GVc5h3rwXtW+t2Jqrs=,tag:JShYqLl/CBaSz2aNU6D46Q==,type:comment]
#
#ENC[AES256_GCM,data:HCtWn+M8afOVVI8H+ZYJAMhdg7gCqHxpIq07skVruabI73+ArrfpgQ==,iv:TpAqbxAVdB/Zc8VYo5pg16ilB6zDjnEoZh1l2tTgFwI=,tag:mYdsABKhtTGViCFuU8SaTA==,type:comment]
#ENC[AES256_GCM,data:aDTFdMGFPTTUwIfPHd79Llqx4aVn734=,iv:JAaLrLRZ370ymcD0RieMISj3bS58Qd3xoWOq3SPUHQk=,tag:NTqBARhHDeVVTtAwrHUC2Q==,type:comment]
#
#ENC[AES256_GCM,data:UimX1ebAKuYMVK6a42eY24Uln6ERTL1AQ+6c8cYDvrh4/2cNC9LtTgISO9o=,iv:hZPZD3OB2ErxodgQmTTeFepjqDHpEj9T8GLbS89WAfg=,tag:y/WEXv3iSuP1/6m5RSUY2A==,type:comment]
#ENC[AES256_GCM,data:ijPBXK5/Khwg5yErA/7a+YXX7gWGelEpdZQOB+DrA50Qk9WxNkdy3DPqsi/H87tGQ1oLuv1YKXtfw/vRJorE9IxY1rEVYKurlghrL01q,iv:FmS/n/yB1YK7WOnazWoEMWCesAUcMoQqftAe2tORaCc=,tag:rmC0zjQ6yg1aewXsM/aRtg==,type:comment]
iot_wifi_ssid: ENC[AES256_GCM,data:lPkxcuTmBNtPETkZ,iv:AiYgUmBInuy+cEuZNnU5ccfcT4LA8a6JVo4MNgNW8fU=,tag:LKCJazWEaSRxUx/3X6H2/w==,type:str]
iot_wifi_password: ENC[AES256_GCM,data:hamrMNdCd8rQk8UWrt4+WUmv,iv:JPJKZmttdIKIUpANp72EgRqTZooBheKV0BBIl1Bqg0I=,tag:66/kVhI5p7jYhP+8mSsNMg==,type:str]
#ENC[AES256_GCM,data:nuevQxO6s6esTu0cHGllQSWCMuZqNK5y9kaarwy74UOUr0Xq74u5/S12j+H1L5+wV4f6A3flG9KNEsmHCeHSHLyl5B/rPlMPTJdT,iv:oLP2msju0dy1Jb0nJUNzxzMgUtD7PY3d4/uiZvCQWUc=,tag:2/TmgnbOys1dlLu6ClXaOw==,type:comment]
#ENC[AES256_GCM,data:lfmZtX09SmyfsWFWZHX9nFzjqvF3r8k0BFUt25k9/VdnShDXll3JxtdRfh8cM0+V/zc6sTUIAWQ5IyUB0qIApjba1lxmCx3HihsIAj1C3JyM,iv:FBJ/nPrWH/quE46iyc8mlgeE2csYN6rrzwUI93L4sJY=,tag:THKjvLiUo/HgA24qMGh9Lw==,type:comment]
mqtt_mmwave_password: ENC[AES256_GCM,data:E9qt6bhUvm800LwJBZrfjvI3FFmVI4Lvltg0NpfcHueEPDTy0JeGkY1MwM1S3/+L/djYnqr98T6EUE7ScP/JZQ==,iv:2RwFZlKL7vn8Yq1F1hbmHNh1pmMlQIGBF2j2ZeTx4nM=,tag:/C3Zo1Ex3ieSq9xwr7cNmQ==,type:str]
#ENC[AES256_GCM,data:+3lru9es44Fe7BN2s0kyKA256ebPgBXYrQOMB09z3kZSiFN3N/+PJ8DZOp4s/aG1GN2R3nkeSsJYEI7ZiN3HXHedwBI8PVG7k85LVMCw+DEXyQ2dwKYB8Q==,iv:Rr/stJ1CSX7bsPqMJdx7geHDMZwl0tivFD3axfahW90=,tag:0Ox5tb6WXQYaia4oSSXXkg==,type:comment]
ota_password: ENC[AES256_GCM,data:TIlgcpFug7y198vH1u7lIL77xKOYoYkXLuTS51zipXrzgnAcWMjlMQis6yEUiiUnp3cH0jepmMbP/h23N9PSvA==,iv:aAmzqp0036QGC7VPfwVB2nanDHzWIuiRkMKYbgSWWZE=,tag:KZEYuBYFKVaaiT1zuMIqkg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MjZsYU5Ld0FNa3RWQXZ5
            NHU5anVHT2lmSzlLWnVRQ1p1L2lUUllNSmpZCmRhUzc4blRwY1R2RytPdlFSMzdn
            dzNJNE81VTJubENCRjRtQUc3cEUwTEEKLS0tIHhqdXlFSXRkbFVjOWtOd3JZcWU1
            QlNDN1lBdTk2NHdSQm1DVnhMcFFqVlkKM49C6WuGWIvW7oIBMNSPGDUPJH7ZrqmQ
            TCpEixLt2Y+J7qHGMQjgjNC63+h8Lkk6UcVMuMmHS0jAVd8bF2hxxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
    lastmodified: "2026-06-27T05:59:27Z"
    mac: ENC[AES256_GCM,data:OFu3lSwXRa6BAuV1PS9XbXR2zTNotFYJpFwMrBndoe1jC07ocqkMMsKgWRJUUuPo0/7v0Y6i8OH53VEjtkBnst0cyPuy9ImpOERZ8EFJB1SzHNnziWvvWrRJ6Hkij7Zye5HZkBqSljP66PoVtA5mfOtDJd92DW7sh3ieuy4U97M=,iv:ZzR0nZSuawWytz8wLX6hWXadLlV5QBmmg7+fkQVE7no=,tag:EnXYTl8nTAupRQi1W/qHzA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
