apiVersion: v1
kind: Secret
metadata:
  name: truenas-iscsi-monitor-secret
  namespace: truenas-iscsi-monitor
type: Opaque
stringData:
  api_key: ENC[AES256_GCM,data:+hVql5ABJ3kkJRpDksUySKXEre9bOpZV93yETdhp+6e1fjT9NsxC2I5UzGcF/JbawFRtD/IjkDF6N8yoFxud/3RO,iv:/vrQFOsOh2Jzm0UJ1A0OSscWTjQqi8x2OS4VDa4Q3Mg=,tag:5OgpeZNGceWIylzAjklqBQ==,type:str]
sops:
  age:
    - recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0b2JSbytZU2MzWHVPQ1Y2
        VTlObW5RMzRwU0d3OUV6ZGhJaE9wZlFlSXgwCkdRYjNjSlFrRHJYRWUxZjR3bWlJ
        RjUvQ1FlQUkwVzA2UG5Ba1E4a2lLRHMKLS0tIFlmSjQrajJkNEI1THdvM0hmSDVS
        U095QzhTbk9EcTBsTUpnQ3FkY2IweVkKNRAzqvV+CgcbVRjpXprzlvIjVz+nABob
        aXPJ7+Zr0FeKJYlXGABFcy5qPM52jZeJEGhYWLXZBksKQcdbipkRkg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-09T20:45:31Z"
  mac: ENC[AES256_GCM,data:zdO6xKrIHG3bOwENOI1kcew3MY5rcYVPm7/mbGdO2ouYmUO69Qa5VikcsPmcuXtKAG331D9GzYMXdMznc7I5AXS7ky3e7dYbw4aczxTV0Y5GgIb4zebbG6Zz2rYKV83/Dzv++JOC0prgOm/Apnxn0scKIlOmw9YV+uUAUcP+hW8=,iv:DzsDBzd6Tq9v9pz2q3x7DHpQ+7c55CwSptBxcFJVZw0=,tag:/RCMMEkVzQgXQFz/fsKkhA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
