apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - configmap-go-librespot.yaml
  - deployment.yaml
  - namespace.yaml
  - networkpolicy.yaml
  - pdb.yaml
  - service.yaml
  - serviceaccount.yaml
  - storage.yaml
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: snapcast
      app.kubernetes.io/component: audio
      app.kubernetes.io/part-of: homelab
      app.kubernetes.io/managed-by: flux
