---
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: ucgf-peer
spec:
  timers:
    holdTimeSeconds: 90
    keepAliveTimeSeconds: 30
    connectRetryTimeSeconds: 120
  transport:
    peerPort: 179
  families:
    - afi: ipv4
      safi: unicast
      # Select which CiliumBGPAdvertisements feed this address-family.
      # Matches `lb-ip-advertisement` (label advertise: lb-ips).
      advertisements:
        matchLabels:
          advertise: lb-ips
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 120
