apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: flashcards-db-production-cnpg-v1-backup
  namespace: flashcards-prod
spec:
  configuration:
    destinationPath: s3://gjcourt-homelab-backup/production/flashcards-sync
    s3Credentials:
      accessKeyId:
        name: flashcards-sync-aws-creds-secret
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: flashcards-sync-aws-creds-secret
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
    data:
      compression: gzip
  retentionPolicy: 30d
