apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: flashcards-db-staging-cnpg-v1
  namespace: flashcards-stage
spec:
  description: Postgres cluster for the flashcards sync service (staging)
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  instances: 1
  inheritedMetadata:
    labels:
      app: flashcards-database
      env: staging
      policy-type: "database"
  monitoring:
    enablePodMonitor: true
  storage:
    size: 2Gi
    storageClass: truenas-iscsi-ssd
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: flashcards-db-credentials
