apiVersion: v1
kind: Secret
metadata:
  name: audiobookshelf-sso-secret
  namespace: audiobookshelf-stage
  labels:
    app: audiobookshelf
    env: staging
type: Opaque
stringData:
  #ENC[AES256_GCM,data:i/+Yr8ZW9LumhrzBMy+WGtqY4hKTWNka6mMmvCojBKMnDi/7vli0mpysS05eUA9WJCw7,iv:W9/7ns0CCAjJ34fwxxy94cHFG7m5RzssIf0K51/SZgo=,tag:8iqp8u6UG0So5PSqCuQBxw==,type:comment]
  #ENC[AES256_GCM,data:2bkKF6ezptCqOI9aZEvgbVkNhHhiA0sly7d8MSCt53osk9NT9n3UGt8iIrrfx6P8oLlbN4zZF1sN4tDICXs=,iv:I3nPlUHhO1UdPvIwrG/8NKQa/0gQ+to+nBXMdUKkVlA=,tag:xpXeRz0DAVgU169Xf7ghhA==,type:comment]
  #ENC[AES256_GCM,data:5qnBbhgLZmryOMDnK92k+MmxmREXEtySqKatDWxk7zTcc4Mlh0w2hWAGROL0GSxK5SB19ozwOZgJcvg=,iv:l9KJSXccGUA4WhfjhVqfTCp2PUlJki3GdpBtjPE/u8w=,tag:GjHDZNw1lv3EM17uXpTtHA==,type:comment]
  #ENC[AES256_GCM,data:15zHkbLwbbMqSvYs9TzgVcKeLtACvuI/T3STkgolQveEQ0kq/V75nBu3cDy5fqzmzv8MRo8vV0BsPbQSvGc=,iv:4b/dnCIADA/CjpTFIKBq29Q4K4SDwWmURwoCql15plM=,tag:2rGhtMe4kic4b8TZff7R/g==,type:comment]
  client_secret: ENC[AES256_GCM,data:w20t9MnITF2azyKiYQL+opebQz/zuSKNF0noG+ZBEsEXB/1t7t8b5ofGg2W2xPYqOwSDCnedsv+ePrXnAdSnwlZOsRZND4QVdkdhSeNjay6w4LzfRDHSkA==,iv:EErXhLJxnC2xAOobmmDfYVnziIVtCXH22y43Z8Kw1Qw=,tag:4rUo8NQfl0L9LB1QI7kURw==,type:str]
sops:
  age:
    - recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZkpUT1hQSElGZkZIb20x
        M1FxbTF3Nk9ic1RZeVZTbGhYSG5mTHhkT2d3Cm81a1IwWEhCbk8zbnJGOUhEeUpT
        RW4yM0o1dVQvbERjQXFBUTQ2UzVEa00KLS0tIEVxZGZUeVJsdm44aXJSdndIRWEy
        VlZHVkR0dlhVS2xQSSt1b2FGRmtGZVkKIOND4SB0HsTonXhl/VEgLV/z3Tk68YsX
        7bmAdQFuOnHtZcnvM48v90WQ52ctV7ADknzoGlb/sua41rP8XYIzpA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T06:53:33Z"
  mac: ENC[AES256_GCM,data:s8Xi+V+Bmcq25tPDbD30JSWT7lR4pUCM6uKVCsCkhen3+DPCvnuwayzscpj62D/5ZDZYQm8FaJWy9JPF2yVwoW0pqf/WEACKwt+jH31x51kBZLaV5hs7ae3tzVHRw3LbigdFCqF8U18u/tLZZ4+VCKYPGhMykUo2LVjSGe+4ngc=,iv:bF6DF9CfEZTx5V+lBchH0NN4PocnpxSYZQxleP0Js2I=,tag:qmcz4g5FKTCJW84zLPALbw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
