apiVersion: v1
kind: Secret
metadata:
  name: audiobookshelf-sso-secret
  namespace: audiobookshelf-stage
type: Opaque
stringData:
  # SSO/OIDC Configuration secret
  # For Audiobookshelf, you must configure this in the UI.
  # Settings -> Auth -> OpenID Connect -> Add Provider
  # Issuer URL: https://auth.stage.burntbytes.com
  # Client ID: audiobookshelf
  # Client Secret: THIS_VALUE
  OIDC_CLIENT_SECRET: "2kORd06055910-e.-QYVBPr2ZdEshWEBDoxVqkoQil03fCBWyWgLX5YDshEzDMquDxnFUTSi"