apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system-staging
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: staging
  # Repo is public; use HTTPS to avoid egress port-22 restrictions in-cluster
  url: https://github.com/gjcourt/homelab
