apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: overture
  namespace: overture-prod
  labels:
    app: overture
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: overture
  namespaceSelector:
    matchNames:
      - overture-prod
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
