# AWS credentials for CNPG S3 backups
# Encrypt with SOPS before committing
apiVersion: v1
kind: Secret
metadata:
  name: vitals-aws-creds-secret
  namespace: vitals
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:6HTb56RYtVEHflT9pf+DC5puo/4=,iv:/Yn9aCew9AwOcE3Ul4jmTF5r3X6oZtf+FYctWKDAHXg=,tag:BTUjcFQohWVJOmJ8Ru0AUg==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:WVzMEDKTNU8zmlBb7cyFAMcS1Zz0WlkHg8l52247BkXnhmVkQELieA==,iv:zB/3VdzXcmrpbuB3NsUPYFMyVu6qxmiIv55Bq5G2sxM=,tag:oZ7lVGVbsIt+W9Mr5gzk1w==,type:str]
sops:
  age:
    - recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQUEyYUJGOUpBQlFoVnNr
        eU9NRU1TZmtWdy8va25wSm5JeWcxUWpEZGtBCkdUNnVGckw2TUhyWEFTMGl2WkpL
        SVUyNXVrbkZKb05PY2paOWJhV0NCUTQKLS0tIHpVcG9hNzZPZ0Z0UEpsdG9SOXpN
        a0dzaXpYdTBCcFBUK0RBckJNdzNhYmMKwQDlZPrZJu2HuQBS5B86apbFY0hLUP5p
        ScTQ7aNg00PzHx7hUyketfkw31QzqNlYUUBFeTBPRvCTp/rRrSi2mw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T17:08:03Z"
  mac: ENC[AES256_GCM,data:iznf4eiZFRohR8HxEFFmGN0DShaLMapYwbH9sEiChPTFjIRh+qH8E9AFhCXbYeMm8u80hwa5enTb+Co9xu9JSPKYC0v6NVIyClJ0zJ9GLGD0dPNYohVevlHcIPvemjvdTYPhVf0a/97/dBUbXlHpbxBItkxnZQCWUE5oYNqsreA=,iv:BMT/0si+h1/jc9rJLgZK+T7VWLHiZWnzH/+UbwtLfdc=,tag:SMOgkTM6jC7tfP7igHtCow==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
