apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: modemscope
resources:
  - ../../base/modemscope/
labels:
  - includeSelectors: false
    pairs:
      env: production
      app.kubernetes.io/instance: production
