apiVersion: v1
kind: Secret
metadata:
  name: signal-bridge-auth
  namespace: signal-cli
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:EuPP8S/wW7vZz1rkBxohtNMqbG+/Hi7WASZSSwGug7dUHwanXvBSBQMX3Q==,iv:niF+AU8wU0P6CQgif0EjO4ylzn7WGeZs1wbmv9SYWco=,tag:/bWruJnE52nxjSlJzI9brw==,type:str]
sops:
  age:
    - recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHL1M4a0xDdDFSdGpXaitP
        YkJ0U1FTcGU4WWwvcTJaVXd3SjJHMm01NkhzCmtZVjlVeU95ZWhHOStOLzZTbXJa
        U0x2UHE3RGFHWUxER2lhdnRxa1NaRWcKLS0tIFRXbnYzWEtDTFJlaVZZZnF3RnMv
        TWs4a0tkYlU2YlV6QTdLOGU0N3EwQnMKE6LlJtLze5DR05rFpFyiexRhF1RB0sQB
        RH5a6WS7VbXK6WnJ7iFrbcsFDBCMD0rZWPl3JViNP33VgFAkxtgBiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T00:51:39Z"
  mac: ENC[AES256_GCM,data:4yRJiMjgHT/Hfz5VpBvYUV6T97f1Hhk7ey5HEv6hYqU7Q5SkkMDPtfpjgX9vOEo9DLsIObUcoj7/uDSHmgtEmYBrDIqvBU4oXkC6beKoDLW4XacRk7E6lIGGiuIm/XDqViNQmBgpFft85WooGJiupit7YSITKfYuabQgIrLRxRE=,iv:C1hE1S1V1Fsh04pj2P8hltU583FwygPPM1j1Fj5tMo0=,tag:/2AxokhqA+qdQBwW9Kg7Qg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
