apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: democratic-csi
resources:
  - namespace.yaml
  - release.yaml
  - repository.yaml
  - secret-driver-config.yaml
  - truenas-version-mock.yaml

configMapGenerator:
  - name: democratic-csi-helm-values
    namespace: democratic-csi
    files:
      - values.yaml

configurations:
  - kustomizeconfig.yaml
