apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml

configMapGenerator:
  - name: democratic-csi-truenas-iscsi-helm-values
    namespace: democratic-csi
    files:
      - values.yaml
