apiVersion: v1
kind: Secret
metadata:
  name: democratic-csi-driver-config
  namespace: democratic-csi
type: Opaque
stringData:
  driver-config-file.yaml: ENC[AES256_GCM,data:zlJyqutGzyqOrfd0v2nLdsGxgL7AmBUS+lybv1Tf5r9IPzezVxEh4y7cX11xab6felyNSlNJR7RGo9YMjAq024PJHC+sque0HEYHg7kLX6mH2E/NaB7Sw2Ix8Fu1YbEE+Y8Q23iT2UxGEUUrqE07+dT/4alcD84ZdEbncvjYNQ7igagmmv92SVZHdP3yEzHNx/NF1HUN1R/khg1RMUgk138fSISQULgwstOABuRCU3sQZgcRmqXOjSUhEaIRmwHCyuCMJP7+RkxJwYPnDzeAjOWzYm9lmahhgDGurEqXPeIjgfNzFKXgq01dVZelsbEDFf/Isk5+/7Po2Lkc8BCxhx8yD3E/zXA48c7jR5hRep7Z/G14jl80S0XZXmDoid+gdz0KlclOqXIaFWLASyhqdYEHBGjJuvuG1QrlZBEHeRYHOu7AEdZe8kozCJokb5/LIrQrP5CbxKQf2jrGCkcSmj/GrbG+2iyVHEOiJdXvE+/bR++1wHhN0+6H+8FGiDUbVah2ScQgoax7CLA7eT02QQYB38dFIiUqDGMGNo5s9HT5CduDbMTSsSFXe7uhAFDB2iTNXHGYGDJ/OccQMRvSfhSFAy0h+tj38lCnTyJwSLJM/oEpCyF2o9gVtbtQhBNDq9VcqvX3YCcwzQ94TGp9SYS5P+l69qiwWx9nGFLM0DKx/602OKXRnXwSDCgIhIYOtO/it/SHarow1jpI7t2sxo65DNQ9wcybbvs2fZVUUKYLIjoRIWRCmAqWO8DcPeDH8mpntnyBG2UUPJfkSMkprMBmakl34UQnqAIBy+7PuK0fG/5kR/Owv589XVjphUk19gPQ0Ber0+UFelUolMq/AizEL0GLGtcwug3i1C81nIojvtZvBVlbIjYb+3x5YQxDudSnMjrhXtT95ERTT6f+JwOGpBXScKUzvVEgnwCPAV3+0OK2pMX449bAdpuha2OMMGRaOXts2u5TxrFKRohOw/3nWk9+W5Vry6f2oTQAV49QSGY+A420JAe7DEQmzt1SwwiNzt2zCM7fAnTuQAR/+vHneU7BOY80DL4NhFlewIu8OH9WGj4T00dKwh6sawxRPOq1x6NomU1oJg0msDCHHkplUvx9sAVzlllybmkb0+G1/pIQKUwxX0u/bjv4hjHXlwEGO96UUAClqBHFL8QlBPNcTq7E/BfdSMqgNW+9LkBYC81ixU47DK8XvbQTCg9uVAuY8OJBXFViSXzxeLfV+djFj6rssJ2cxOIZD1r3L/t+TolxxewrkC9nuvvfm2I/aad2H7AWo7w5Bmn8v+m+,iv:5ePCRK8vrl/41sSsaRNX/M8qepG7Z3EgQBjZGjaf4ws=,tag:54LiZrNj1Xk9T32NOCJx9g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuT3FQTFJCM3huR0ZTZitW
        VU1iSnZHdi96VmdNTUp2U1pJWDdwa3o3T2prCmdIMWNOUmxTTVJuMnFCeEF6UEc0
        VWdBYnFXUlQyYmNSRHNKVUlDd1piQ3cKLS0tIE1idGRQUmkyS2dHOW5nQy9NZFdq
        TFRsaWJwY3RzcEdZVWdQNThMNW9KVGMKe6i3yIAB31mvZGpsDRKDaGUBHkiapM5J
        eR+gGAXY/o2WtQ7ELfNWFRkMU/Ix8QhCkXH/DQFNwh5zu05FNM1YFg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-28T22:33:13Z"
  mac: ENC[AES256_GCM,data:ll8PFQPgVyiZh+0McJqhpCD9GqzyZpTCLRUKVWmvO+ZtOLt4E2oitOfEXeJzwRVgqy1qoJilr9fJulPoq3xY/QlRy0y2uQJli8z29dWIKFbL4GWNbbzSyitfGImtIYXJAyLHvSGIIOQOiVounyYeGOpPOLHjjILdNxKHD/I8sTs=,iv:2acdbxbvLFOU/vgBLfWK48+wlLAoL8Dpq0Uha/t0S0Y=,tag:JCO8Dpl2kfvQYoGs5wmQGw==,type:str]
  version: 3.13.1
