apiVersion: v1
kind: Secret
metadata:
    name: truenas-api-key
    namespace: democratic-csi
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:uLbst7hwlY83mgxdkTfK+goakpzDyIyh5iyRKiX6kv8S0jPaPi49jVdaAGnAXvbiw/npWvnOkatry+dkl6i0gMc3,iv:0rtUgBrU/iBCIO5K/za1Z5KCrPvztPGTOuJpRFgZ8jA=,tag:jgdfi/Hv2Gyq1huaWkzCYQ==,type:str]
sops:
    age:
        - recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkYTBRQkVNS1ZlSHpqckxN
            Y3hMczM1TUU1eWp3aWVNcmVrRitzdlg3TDNvCkxKLzQ2REZ2Q2psUE5oVi81WU1D
            TDVOOXd6Yk96TzNUbHc0TG5kOGdWdkEKLS0tIGtLS2xpdnlIWWVqelpqSytJSzhB
            OXROc04vUW1PYjBLRmwybWlFWWpvVFEKQzjh9oNdXDMje19HkGRURpncKVKSu6Mw
            wU/7OWOGwhKlqN1Lm2EhmMIG+gOqrE2AnkVo5GyhilAL2R/UgZaDHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T23:24:05Z"
    mac: ENC[AES256_GCM,data:lg2CbKrGJNVfU/+OEenHg9tc+5XOKohtwwh7CjKIwa6MATqy1sl978Obr90BxcGsXNLJiXeMVHB5g2nDd0pJq+/+co9o5maE9Igky3Pz1pfPxUKvKEfyuE41OHEwEMKbAR2TMC1NUZU+QidY+++TCQ7fHj1DtJl2bsoTJtTpk88=,iv:1Ltg3lWLMJ1a2xQeV1TNb3mKtIXZvIGOGl2QJ7/xyHg=,tag:nNXNuhiOkbUZcQi94/l7iw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
