apiVersion: v1
kind: Secret
metadata:
  name: adguard-sync-credentials
  namespace: adguard-prod
type: Opaque
stringData:
  ORIGIN_USERNAME: ENC[AES256_GCM,data:9uWN9ZlW,iv:qaxeJjD+yPSX8caW/pxD9sw9JkApCqZd0zvSEAjUL2M=,tag:5U9fU9OZMKrwBtMFtlyw1A==,type:str]
  ORIGIN_PASSWORD: ENC[AES256_GCM,data:/cN9tmkbqdKe7addueXLROEH5g==,iv:/IwEjSyp2HHZMZOeWxnkKMM/i29fmz0YLjgI7hmnbeI=,tag:XC7D95m6uvvIccfE9LyDBg==,type:str]
  REPLICA1_USERNAME: ENC[AES256_GCM,data:2H4YmWwj,iv:J1mkW9x7jARIc4Bb8A9s2jUBQAeNcpZrR+o18khhUhs=,tag:uPayBS6epFpCLBIIxLgczw==,type:str]
  REPLICA1_PASSWORD: ENC[AES256_GCM,data:EdbNEAoNTEIhgtcym8tkrewYTg==,iv:aIcE+Qll+XF2mWZWar/7YT7ldFSx6GPMQ4qlElPK+LI=,tag:UOALVzDyX+wqlQSe/pU0nw==,type:str]
sops:
  age:
    - recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZnFBbDlFVXhhZm8veTJ3
        RWFodHRtcnRyYmhGcnZIMXBiQkFRRnlYWDBvCkFVdUt6ZEF0b21XNzdvSyt1MEg1
        c3IvNFFjSU5JQ0Ryb3VsV29CcW9ZbWsKLS0tIFEyYnhndnhwRmQ5MElzOEVOY1NY
        VzdLRThoaHJubi9WN1J0Q1ZNRE0yTE0KMwwlxcoWUdh9yV2o9iM+u8w+qQlkfzCL
        FLHB4enL9s2xTc7QI3OfYXs39GqSO5yThiDQVuFG2SyebAxlxELs8w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T18:11:21Z"
  mac: ENC[AES256_GCM,data:6WZC0+kmP0N9oB0vaSjytQv7fpm2Nko3FyTKa231OnW5jBecmE9PphEFoXvWKjg6F7nIwJeAB8tg5Sc2pZAmXvEVlfIKnIMnQ5D7pB/qIwqwjBpRIQIEBQCl6w6m8Z522gbjRvw9Vy4wSP+RKVp58IDlwEfqrcoznmASFE/nKtU=,iv:VKqxBMcSMB6iBMc8o10OiIHayfq+7PtgKBNL2fnIORc=,tag:6/hkgzvjtk9Vh9e6pSD0lA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
