apiVersion: v1
kind: Secret
metadata:
  name: audiobookshelf-sso-secret
  namespace: audiobookshelf
type: Opaque
stringData:
  OIDC_CLIENT_SECRET: "Ha2QclfgdZnTCbtJI.SAfrmnIyn782Q34bH_ljlQYcrg.F2Lj.zWeUDMyulE2uRj9G1fcYgs"