# AWS credentials for CNPG S3 backups
# Encrypt with SOPS before committing
apiVersion: v1
kind: Secret
metadata:
  name: golinks-aws-creds-secret
  namespace: golinks
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:RQLon1kIwYEO99i8CboYWTbVA3c=,iv:EbzUgJjE8D7zetTEUx8+eeCOF9Adpaf2gWTkxUyauOY=,tag:jLYQtRAiPcNpl6EPgmcQdQ==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:D5D7SM2Q1W6oYXqWQtlil/kor/Pjqsmze2iFf1d3kQs5b89lTIoRUg==,iv:ThJGXY0+WD3sVaO0fiDSQMguCuUe5IN/hB2xt5jqUaA=,tag:tJyXj8WzPw1/FWN74or6Og==,type:str]
sops:
  age:
    - recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdXZ2WUQ3YWlqVGZWd3ho
        RVZMaXJTM2JyNTRwNmsrRk9zeVRTZ3l3K0ZzCkx4R05BQzhFek1jWVVJaVJodWJN
        VjJjL2JOTHQ2eVdKdGs1a0UvS3QwNjgKLS0tIDdZQmlQek9zSjVjS3l5UXN1Q1l4
        QmRzT083N3RzdW5xMjFVQTRDQXFkU0UKZ11/KHpfX1L/Uu1w2n2q9U3RH+F3K7SC
        pbaKSm55a0YGcDXrdj8sZPLSbbBXCmWGqldJwgtbEGHd7gVcxmu/Zg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T17:08:03Z"
  mac: ENC[AES256_GCM,data:0RYvn/obtn3uJAojbvqffCdHS9omx17Wm/Tfc2vBFFN0Av9WlaDAyMrNTFagv+5tIeZpT0NAudfBbQNvdM6AVpG9mFyv6quD0xht9xZe/AtnsSlUqKKUrvHpOx7o1doj8k8T2dQKgwNceyNrHJMrVPqKK0ZHYvtnGRrPEzZj9zE=,iv:Em2o1xAB+yDCFHDQ3dppM6TiE2HxU/o/rtgh6rupAgg=,tag:QlHVENP0f1fbsy4HMRN3Hw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
