apiVersion: v1
kind: Secret
metadata:
  name: linkding-oidc-secret
  namespace: linkding-stage
type: Opaque
stringData:
  # Generated for Authelia OIDC client 'linkding'
  LD_OIDC_CLIENT_SECRET: "6FPq81DraUNBshQ7F_6xbNGc8rsUQZdYafIJYjy4zd8PXX-e5WN7R20LgOLDKox-ow2EkfPY"