apiVersion: v1
kind: Secret
metadata:
  name: linkding-app-secret
  namespace: linkding
  labels:
    app: linkding
    env: staging
type: Opaque
stringData:
  # Initial superuser credentials.
  # ENCRYPT THIS FILE WITH SOPS BEFORE COMMITTING!
  LD_SUPERUSER_NAME: "admin"
  LD_SUPERUSER_PASSWORD: "Sup3rS3cur3L1nkd1ngP@ssw0rd!"
