apiVersion: v1
kind: ConfigMap
metadata:
  name: overture-container-env
  namespace: overture-prod
  labels:
    app: overture
    env: production
data:
  APP_PORT: "8080"
  DB_HOST: overture-db-production-cnpg-v1-rw.overture-prod.svc.cluster.local
  TEMPO_MODE: real
  TEMPO_BRIDGE_URL: "http://localhost:9877"
