apiVersion: v1
kind: Secret
metadata:
  name: overture-aws-creds-secret
  namespace: overture-prod
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:mde7fFnjQUAqSpHrQWRSGXJ60FE=,iv:QkZTKWhAKJb3ZKRrjkDOTETvAnFWao0ro6EbGlJJ2I0=,tag:+vDoUgXSj5vUvt4XplZCvg==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:rGDqbiEQxNaBTCsbiepKl2v3hvurRmDO1aOkXcofgqsef8vyOCBUDQ==,iv:CqlVJXNtLk52QSQbj7kGMo4YuVZ8vl1UKlGKvLrp/dE=,tag:Q27lVpr+7A7zk8gyOe28Og==,type:str]
sops:
  age:
    - recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMa2daeU5xOGg2cHVIdmNB
        S0phTzY4eDB6K2h5OXA5RjZxOHN5UXBPVFFZCm0wVC9tdWdFeDlSbXNkeFptYjc4
        YUZmaTl1WDEzRC9kdmJMVDFwUy9RSzAKLS0tIFFiZDNJV1YrMHBKQ2RhWHpDY1NC
        YjZsU1Zta3ZXWEsrNGNDeXRoR24xZEEKR30MLkxju2CBrVzpzx0p8N0C8tlEiTzk
        xgU+bnszx6eboCrQXSzw6llv3vI4Wb3fkVRzxtVgUyMKv/+MR/8HVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-29T20:47:53Z"
  mac: ENC[AES256_GCM,data:DODXTxnRCoG2TQrC3TREwHMIq0w+naW/wqJZtfvDsEm8JOSvnTmO0SvcESiReeUsL3khM0kl69KMIRy+WtcWzLvSTD+0+a+D/uhyk5pSrGzgB5NHXG1pdXbsnAua1BmD1EmRsMt2H//V8R8rOO6Vz3e5DiEBqLn9ERR+6PPEO6o=,iv:daEwz+ailO8ckqQCkti1OpaVyw/Y/6D9A1jPbijNtLk=,tag:qLUSkeuEj5x6bd6TYpCm3A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
