apiVersion: v1
kind: Secret
metadata:
    name: overture-db-credentials
    namespace: overture
    labels:
        app: overture
        env: production
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:VNx/,iv:hs5ycVFtN4DcbP66cX7ICwOGikVc9X9TRm7U6PF4ZMM=,tag:cybfpnoubAj/fr2lNcBxvQ==,type:str]
    password: ENC[AES256_GCM,data:8G+KK3VtUcLXSF6UI3snWbfKaLb5siXBKRCG4cCJvPY=,iv:zWpN4Wpt5KYc2npU4yMqDg2ZndT5z3dXT7Xob/GtCXw=,tag:e212fuIhw8ilYsdo6gip9g==,type:str]
sops:
    age:
        - recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWFA4UnFka2FUMmZpd0NM
            WXU3TU10KzdVQXNwNVRqcEZ0dEhJNWQ5U2tZClR6OHNFdEFXSnlLclhkaStHVkRx
            U1Y2TDBrQUNPNVIvUW1Nck51N3dBR2cKLS0tIEhPWUlHM2h1T3dWdjFZcG1lU1RB
            cHhLWUdUWnpYd1Z3Zzh5UWJhQnVMdHcKqsm/IRqnPecHqh6wA5ioO3JBIJkJkKAJ
            aheWil5YG2jUc7AmvX0+2P3UGKYcsIb+OpZhgh3zRlOK8S3tq8TDGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T18:04:43Z"
    mac: ENC[AES256_GCM,data:zLq03uuWy+omCQD+VNyOtTaYp81CsK+3S1RvWosD+D0IfhMYqsntno8sn53ter1yf2C65hBIRLOkg8us6m8CCps5ZkCcu2darbI0qUvDsLesXuLxohIrfxzQ72qxEnuOcHazDE3xKNf4OiM0LZBTlflFCBshXQIjdz71ynZjJtA=,iv:aBr4lSbIOMvYqAo9tl7GOM+MWxdJihMiR4av1NxG98E=,tag:BX8l6L8Lkt+DBEpt4sdYKw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
