apiVersion: v1
data:
  client-info.yml: ENC[AES256_GCM,data:0wCqgHM2fyTNJFQxYNGrFGxfQAe5DTZPXBHkLl0/eNmIvbsBb3FzAyk44ljq2+OjJlYZv+HE/hVa7lefN9pwCcnmhZoboXuIFgWEN8mO6ImhdL3St5KmuHCvIUx9YUi2Xb4i0mK1qIUQ2t+3BpzNUWW3eH2V7Lji23hZdveP/7OYRWzJeFwB98WubfS5wxRLi8FQ6v+WsB6GyrzltO6TviCvNocfNk80ysz/+0p2I1Sljiru,iv:xD6tTeElkbUWpY2R9SVTa30Y80LSRcZ5wUEenfOjJKY=,tag:wsUhf3y/bdXrc2f4JyQKog==,type:str]
kind: Secret
metadata:
  name: client-info-secret
  namespace: synology-csi
sops:
  age:
    - recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVzRVT0NDMVcyS3llQXo0
        aVZBejRMQWsxOGt5bVQ3TmpHb2FxaTMrTzI4CmJnN1hEaXM4Y2UreEx1SUREai96
        Yyt1aGZmbkFtRHFzVkxwWDBXV0NQcEEKLS0tIGFPSmlnTXV1MWlHUk9sMEJISWdK
        SGROWCtKMS9aQlFDOWZMRkhPMUhxWlkKNUX5Suzf39f7JFKhyZSJACiNyHSzkZPF
        b6DTiL6EbEjqCQIun7pmL44fxlRhJdWsBRdw3mQ2HLs1HYhNGJu6kA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T17:24:37Z"
  mac: ENC[AES256_GCM,data:B76j9yxelEVHO4nZQvm8gHLgtTlVK7D8eTsKHQPCWVXVYD33U54HfP480F24A6KzfRJpSJSu5oIG1YPdBrw4vDYw7rA1k994tEfXNGPLaLetUGOxeWaKb7aZWpVZmoBjMKh4Fbh2ib4zFTfRFsOtLFlpiP3q83RFgFi3R37d6WU=,iv:Anqtxnyme7e7chSXa072EXACUQQl3XjC6vMCCXUcO+4=,tag:wORejdTzQ8A5AutoGj66CA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
