apiVersion: v1
data:
  client-info.yml: ENC[AES256_GCM,data:kBOF8Aah9ArXlkK9f384i+LQ/9X4RiJXWZx4M6IkU4gqUaxkSezMnW9RSjscYNbAoElgVUm/8YqcbG1akxbTPqW63Xhna5KYLIKb7GpxxovRIfJ7+6TrtB6+zcTbCXPBW3aMZ5vFV28rBIe+1jhZ7SnDU6ZAphODnmweeux6SLoJ8NlcHHr7WD4IuIvGRjZrZJj/OwkYcKKwbAywAs3AqzErpTMt0eb95VcG0WfzwUbFpP1s,iv:zsWq2oBWZsKKrMZuNs5RKkEfAbS725/booW25yapNRY=,tag:WofLvz01lbRfSInzG8+IJQ==,type:str]
kind: Secret
metadata:
  name: client-info-secret
sops:
  age:
    - recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMnE1RDgrUjRzdmdIOG0v
        ZG9ZNXlHa0MvK1A0SWpranorSUN4cVkrb2tJCmtjT1ZKYitUaHB5ei8vRWNyKzZ1
        eDM0bjh1aFdMOHVNMGZCM3ZlcHJqUkEKLS0tIDZKSDI5UjBHdkIxZW1vWFZsR0Ni
        VUVaK0h3VUdYbSsvZWxtemd2VVFoUm8KOpwEgRf+esrCK9uxknKvglXON7+GqF7j
        mWaB1uTIspPhxNTB1SP6iT8UovZnwlNoQDp2ksqaslIQA5mBbcIsKQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T04:13:40Z"
  mac: ENC[AES256_GCM,data:/KMKtX+8hnQ5Hj2sWmDlVoHhYQaCag7AAe7X0KkDHzR9hVJTM4zzuJsHiMJsa0/Eb5yEngFzIQNN2Et7kxieLpL/yFyEfmhasjTORYEORSQ1ULHWA1RQwbHulHpAaKK7ZCCgjcL+fJ2qu2o7PICl48gpahizF7lhrDslBbhVfmQ=,iv:Yc5LmF3tb/O1+SGbqsNqapmMAw2vKlrMaKv3uxDmZpw=,tag:Q9heFxDwM3+c21CUf8miRA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
