apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: security
type: Opaque
stringData:
  #ENC[AES256_GCM,data:+n7nL9avYk90A6/yMlHMae22hM0mUP6MpHzpViMTYkN3yuv0AIDaEhZBido6jJ0Co2xVUDAZzBG2s84fzCxdAN+uoKbypd9kY/Aj,iv:Ebbt0XKgWh9p5lYaMKOslp4t5US3sBD8icwBMi+ErQk=,tag:ok1ZxyvhZSJal70aBwNjRA==,type:comment]
  #ENC[AES256_GCM,data:nckQbVYLUWnyIgGEC+i1vgcMw9EQphvI3abF//FhhJzjeC9Ghe2sUy0td7a3kR1w5dliU/Dg/T/V,iv:8lKJOlEXWqCJg7Phh6VPNnDKr/+FsXnCHWAxQ/6h7/U=,tag:nJAIs/o62OXCYaTBIAomJg==,type:comment]
  api-token: ENC[AES256_GCM,data:52KV79qqmxEKOX2UD21fIq3hBkXEOdP6hZB3rqHOP4POB55FFMjlSw==,iv:uiVjwSCyJDSC+LWqny3B4NZ8DaBgJ3BGBDR2Ps1ItVs=,tag:wQqHM9t5SG57g5A8XBFP4w==,type:str]
sops:
  age:
    - recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdml5MExDWnd5YUkvTDcv
        elh6NytPYzljaEhpRmN2bnNKZ3F4TzNoWVEwCkJmRHZORlpxdGhrUTcyV3l5Ykx5
        bmdEeWE3TDhET3RFRGJFT1AyT1hudEEKLS0tIFhQWUJKTlNuNmdUR0lPc251aEQ4
        c0V2NERyOHE2cDZJRjhuQUZIOGZ2SG8KgRsmVDntaJCNElqoRpkNE/b2RL6ycRnk
        0Tn+o1iDkQXtsyQ2cMm/KWldFVW7NtQo2dUCeXJQ7OuC7+L9d5UM+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T07:14:54Z"
  mac: ENC[AES256_GCM,data:6CViL05zgdygWiH4/hGFVN2/86gMazZjdnR5bdRWlZQZ7JGA3p+xOPBW2qK4upEFFngOkdX97yWmLGmQsu8di0k5hFqwoN8DdYoVM8/d9oEYHnRiJFyFjZrTSVrt8swZluKwg2yvdZLdPYxb6Q69pElDvMuyGvlCB59ZxnTC7Kk=,iv:y0ettkicJMIZzkZh/hobkPS3wPfPeh5MY9YUMdoenX8=,tag:Yvp81wwFzRMYM2SCrmDPgw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
