apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adguard
  - audiobookshelf
  - authelia
  - burntbytes
  - certificates
  - changes
  - cloudflare-tunnel
  - excalidraw
  - external-services
  - finance-dashboard
  - flashcards
  - flashcards-sync
  - golinks
  - homeassistant
  - homepage
  - homepage-clicks
  - immich
  - jellyfin
  - ladder
  - linkding
  - mealie
  - memos
  - modemscope
  - mqttscope
  - navidrome
  - openwebui
  - overture
  - snapcast
  - thermalscope
  - thermalscope-smart
  - truenas-iscsi-monitor
  - vibrato
  - vitals
