apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adguard
  - audiobookshelf
  - authelia
  - certificates
  - cloudflare-tunnel
  - excalidraw
  - external-services
  - golinks
  - hermes
  - hermes-callee
  - homeassistant
  - homepage
  - immich
  - jellyfin
  - linkding
  - mealie
  - memos
  - navidrome
  - openwebui
  - overture
  - signal-cli
  - snapcast
  - synology-iscsi-monitor
  - vitals
