apiVersion: v1
kind: Secret
metadata:
  name: homepage-adguard
  namespace: homepage-prod
type: Opaque
stringData:
  HOMEPAGE_VAR_ADGUARD_USER: ENC[AES256_GCM,data:nFS7z+2c,iv:z2qmPZtMLHUrIiNf37XEILhxOP8psLjdBgWPVSW9aAs=,tag:XdJtoMJ2diA4Qyc1NfMBhw==,type:str]
  HOMEPAGE_VAR_ADGUARD_PASS: ENC[AES256_GCM,data:PPQ3zzeMolbikMtpmjN1PY7Nng==,iv:iR6eF48ZxC1AVVTRjUdD2mMKjoWROyaKb1Auzdq8VU0=,tag:VDB9r9CYKzKwRbsKFy7csQ==,type:str]
sops:
  age:
    - recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSDRMaXg1WmEyRDliRDF4
        eDdqdUdmL1R3RWM4MGRKRmlSdU5tcjZJbkdJCmdPS1pnbG1iU2hmU2NZSm93NTcx
        U1IxcGozR201dFRaVDIwZDMwbUtVSmMKLS0tIGdLY09DeUo3c2lpbXVTdTVyWDhY
        VytkUUp1Umg1b0ZxbGFqMmcrS3VRMXMKKq8fge8+LdxFS9qlUzyFk4LFov/dc9FT
        UTZq/lc3asgAMfJruPDWJp38xJoOOufHoLPCgPRJ4DrPdDSa/HUafg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-10T22:20:28Z"
  mac: ENC[AES256_GCM,data:kjjATqdjSJ+IbRL5mC6KEWAnhzzlMOWvYP9aewvY1nUUsNUtCBsDe4iyBT8WIUwGNmXUyfRRU7Il//OkRVSznCNETfoUP42VVgGh1MVi7IFfX/G0XbXNci0CkdonH8JVPhNMzTO3mEqJZV/usqMcF56Wm15OgB0rZrSdOatdCTQ=,iv:6baRqelh2chWsrKMO1mqw89hcvj4yiMBPGmiZoMZUBo=,tag:MvjBTWFUc7AFidaleow/Yw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
