apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netscope-stage
resources:
  - ../../base/netscope/

labels:
  - pairs:
      env: staging
      app.kubernetes.io/instance: staging
    includeSelectors: false

patches:
  # Rename the Namespace resource itself to match `namespace:` above.
  - target:
      kind: Namespace
      name: netscope
    patch: |
      - op: replace
        path: /metadata/name
        value: netscope-stage
