apiVersion: v1
kind: Secret
metadata:
  name: memos-sso-secret
  namespace: memos
type: Opaque
stringData:
  OIDC_CLIENT_SECRET: "lu5BqDfN_I8HzTvUsSZR~9tH3JSp~~tEULc-EOFfiwt~MKB1ISSnA4rQkUd~XgUuvioYGM6b"