# AWS credentials for CNPG S3 backups
# Encrypt with SOPS before committing
apiVersion: v1
kind: Secret
metadata:
  name: memos-aws-creds-secret
  namespace: memos
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:sP4e096sL94x/raCaH5PAoTmkmE=,iv:d06TfUcZWx1EU/CymobME1cFW6aB097n4llhCnzFx1U=,tag:ebhV/0rnrwF60uDNiz+jLA==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:ZrwedeJJyWmf1k6Pt6wjWfQYvSbgNQRlwANuqWUKUDE3VkhH+wWxpw==,iv:z+kfmnECgrF7JzhVkKQyGEiP2dowtWEro7MjrfObQ3M=,tag:etUWzlG5XF6QET7GfsHGsw==,type:str]
sops:
  age:
    - recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VWtnRVRFMmdvRG54aWJ3
        MEFXM2t3ZVluQ1JlYlBVYlBERHZKMjhtT1NzCmIyZldSRzVhN2FBN1Q4MG9mWmk1
        S1diTUlObmQ5MjhUYWdtakpXQzk5bjAKLS0tIGpnMXp0WEF4OTIwUzF2ejh5NElB
        dVFWQTJscTE4Um83MlNKclJFVzlGQUUKbKhAOEtrVN6yW0k+Sf8YodyVt64AmFN3
        PJRMFazJFo/N7lxKotFWVkvF1s66UzFsmQXETEwmCKUOHo0qSnZtog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T17:08:03Z"
  mac: ENC[AES256_GCM,data:Uz3eg4h1/YHWx1bWcFEBRulaRsWuwRDSIFPCcpJUnAXAo26xOoA5nK+A2NTtXl8cbGUawqnQNEgQ9trihUD5jTpDk8LrOrqBL/AS7iMgtgeR8egu4ZP7F6jgIxFf0J8Onb3u0A+Vj7qV6DKB1YWMJ7DTsj5CHEzQMJLAUOr3+Ik=,iv:QI18mZNW5jBknNWCvYC0hRRZKqxV1kEPN+Sm8343INo=,tag:1LQXXZnUD2/vgsGnHoPdVw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
