apiVersion: v1
kind: Secret
metadata:
  name: mealie-oidc-secret
  namespace: mealie
type: Opaque
stringData:
  OIDC_CLIENT_SECRET: "yC0v5d.gCknxfbl54_dyvm0N6uCJJ_aFv4ZH4QkxvGjPTncNbeDprzQZZ.N7lUUxOL1veLCp"