apiVersion: v1
kind: Secret
metadata:
  name: mealie-smtp-secret
  namespace: mealie
  labels:
    app: mealie
    env: production
type: Opaque
stringData:
  SMTP_USER: ENC[AES256_GCM,data:FzAXD8IqovK93f7c0MRiLQP45CTMDQpOuWCjba3SvDeF,iv:qrD9gu7n8q66nUwX73d69lHzn0fp5DS+ya/mFEo4YnM=,tag:9UyuwaZ77qqC87gqdNgOAA==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:5PU94lmPbJc5cTYfuRnOVQ==,iv:08BPhhN0IlqNNKuwkeKfclfFZ90KoVi/qWtsCxSEzKg=,tag:+z2pa+i0w7deLlt+vX6zMw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcExLdy95NVloSGpoU2p0
        WFRqUm1PeFNOeWtQVi9ybVlCbUZSUEVIdEhZCmZ6OXFXM2F2T1ZoODYyRW9kN1hr
        WHdWdVNXNi94Qnd5eTJjTE5DWHBuMTQKLS0tIDhxVHBoYnIzem9oYnE0OThSaEM2
        NnpMeTFFVDFEL2MydERlUFVvcWNkTkEKDo+J+qGoImYpxdfVp1adgPPFtzTvPcGf
        Og2kYP37W9r85Fi6lBp73/sG7fL1bW4NIbcL1T4QgaXGdFrX7BWLGA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-28T23:57:20Z"
  mac: ENC[AES256_GCM,data:zrhJgKrTmOOoxJVxi/3fXnVIXWlOa2ceONkIi4ZwGWkRg/EkOjKh7FPjRrmNMzoY0UtY7CM8EoNT0RWw6adluFBXbd0/ou1iyfwjtHMjah27wBH6w/7EmEQfxplPNTdjtalVJwMZnPYxHq8Oi7TQrfbymsDDZ7H330MzBqcBCNE=,iv:WGsiev523Hg53XQRTRYysQTzS0ri4bFIep3iagPeKhQ=,tag:hj4Lb1y9Sw9E4Cgj8WgY9g==,type:str]
  version: 3.13.1
