apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - networkpolicy.yaml
  - pdb.yaml
  - service.yaml
  - serviceaccount.yaml
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: homepage
      app.kubernetes.io/component: web
      app.kubernetes.io/part-of: homelab
      app.kubernetes.io/managed-by: flux
configMapGenerator:
  - name: homepage
    namespace: homepage
    files:
      - config/settings.yaml
      - config/bookmarks.yaml
      - config/widgets.yaml
      - config/services.yaml
      - config/kubernetes.yaml
      - config/docker.yaml
      - config/proxmox.yaml
      - config/custom.css
      - config/custom.js
