apiVersion: v1
kind: Secret
metadata:
  name: pingo-secret
  namespace: pingo
type: Opaque
stringData:
  #ENC[AES256_GCM,data:ZdaGfLWZrAdg5Lvj7EQzYrn3hTSpHPYVchNjvvKK8R+9tluHL4vo5cSdY9fOYDZ6XwKRBC7CmAPLLG6UqEOXCXHjqWE/bthp4FVT,iv:NJhHJzme5U5lUOjsWd3kfqeP0nL1ISTGhj81kcEdaP4=,tag:mvhBgWAB7tmWBRil7clHPw==,type:comment]
  CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:Br7NoWo8HCo1ASDMbBKH2lz01cDGUmEWniEClghiGj88vIqlF6T+xA==,iv:eD56goe+XSE/pkq8+E9qAe6K96l0fP0Ze/PmLhuc2Jo=,tag:I6TIlCShL/BAMwpffRZ3Eg==,type:str]
  DOMAINS: ENC[AES256_GCM,data:kBPbuLVvjdkSJlDAznPNF9WA,iv:RCvEVQp92QlK9xm3WIX/VwYVmLom6RJiRHunjFrvdVE=,tag:JgvLyqeiJCPtZ8Irc42deg==,type:str]
  ADGUARD_URLS: ENC[AES256_GCM,data:+yAVED/MnjBDAUgANClyXBhQYPE/HQYfKsH2ZF9VW0fK8C3ss5MAN6hNBDMeeJxA8EK/Q8BG8xA=,iv:/d6L2ZNQGl9e9itH37nFZ0k9sR9TiPz/Y1KeqZ/KWlg=,tag:jDct39InmhBWiBwtoJSECA==,type:str]
  ADGUARD_USERNAME: ENC[AES256_GCM,data:SjhWnM3A,iv:MOC2r1pZmKwPhtaM186Zze/+DlvJvujT5YPmlr+D9yI=,tag:isjjBh5s+bLQ+RgzEsIvNQ==,type:str]
  ADGUARD_PASSWORD: ENC[AES256_GCM,data:8nqEMPrikrrp/DVnRHmeb08O2Q==,iv:bNSnxoX0HbgL0zM53pCd9ZbkyczkRAoDZHpQwkZhvHs=,tag:uJ0y/Zsx/hKCKWUl22AEAA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWnBnby8xZHlEVU15dGdJ
        Z2x3bEZtemRRNUhVZlFmcWZOUEUwVXEwOFgwCkZ1eERhZ2JWTzEzazFnSUkwOXRK
        ZDhjbDUwL1hqb1JPZ2ZmSE5FN21jU2sKLS0tIGNTeDJ3SHUxaWlyWlQzRVBqa2tT
        VTlUMEQrTGtxZWFMckhobllEb3FScGMKBs+a9sd57RnngMTlO4/1Eb0Uwy6/Egag
        StdnnOcGcaQnz7Jauwd4GTnWra3TLaN9ldcIyBmj+X2STz/NhJQUxg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-20T17:11:44Z"
  mac: ENC[AES256_GCM,data:nWduTYiOYJoHLc4Lz8++XqB9tDaHUjnarf+q6Es8TZj+31PcxrRU3NGQZopWaaSf4lRzf+f3jHeP5FfxlEpYPUhxK6HwP2zjG5joHDJsswinfMv0EM+B6udEaRlG7pYNV6BBpM2gkgJ9WQ4X5noSwWCiSVl+2kzootsAlQz31o4=,iv:khiUyJGMe+WLHXG5Sj/gC1FAbivQd99QSKDTIfMF7A0=,tag:b7Nyu3ktbXA4v8a6KV7B0g==,type:str]
  version: 3.13.1
