# AWS credentials for CNPG S3 backups
# Encrypt with SOPS before committing
apiVersion: v1
kind: Secret
metadata:
  name: vitals-aws-creds-secret
  namespace: vitals
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:yGiEHtChueB6Q33u4VdbOSKVidQ=,iv:gHSLFS3MJue+fqQBQCyGvAeSE60SFvtKiBBraKzgU1E=,tag:nRqaNwq+f4WPJodi/4KzOg==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:60k5dpc1W1CNUJcelKTkpztEw4/FRDKBP0mHSMVI3wbpr6xAAtVjfA==,iv:1revTRQ+ssKMatUMxfzFJ7KqpgaMKlNqYefehuc2KZU=,tag:+WCNClOw12VxDR1ZYP5O4w==,type:str]
sops:
  age:
    - recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZmZ1ZnRHcFhwbnpmMDhH
        STRVNklwc0l6VmZuckFEczQ5eFdmTFl1VlZnCmcxNGludElGaDZVK252TWgzSmdF
        Q3lxYndyY2tXVlBHRDVxUnpVWnZEVXMKLS0tIGhvZ0FaOEx3RmF5VnhBaTNZZWQr
        dGZlc3ovU3J6b2VqRFc0dVhDVkRYSGMKJxI5tTrsI/Y4wRjFqm+rT0pqMLHFA9kY
        yXXDZFXfy21oYCuCbz4OR190cNGyXQPEDD5Thfkooja9cSNMx9FYYw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T17:08:03Z"
  mac: ENC[AES256_GCM,data:G53BbIExn9QoanKaZ+OqeFz5fFT/CsM+dAmy09teNr48HEFXBgBzi4+xT1H/o3+TzJmRjErEc4jGQSydJb5DvxuMipXnyKcM3JBnEl8klSdrH0PJ9qukJ+L6GmafbanfnyGCFRVaiNzShfF86djaCqrbkEcbsxmC5NiOtiToo4E=,iv:lMveeuyS0es1Rc6Fg4uSFSUs+rAKO2oqLrq3MwQZ87Q=,tag:zlx/7eA9tVEwgFcsnILiAg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
