apiVersion: v1
kind: Secret
metadata:
  name: mealie-smtp-secret
  namespace: mealie-stage
  labels:
    app: mealie
    env: staging
type: Opaque
stringData:
  SMTP_USER: ENC[AES256_GCM,data:QPs0Z3OWKAF0XF8mliiMmQHQ8YPkd5pzMNANOy04,iv:5uBu8SJ6esOCyDVOLEgsF95BcD8Ex8dYqrofvX6aRuw=,tag:Oa/6gF9ynrHqq2BNFqc7ag==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:gwLXY/qWjPnzPnorKhvP3A==,iv:KKqdXvZBcpD22YfgkxXDNn3/75/e7VHOwpGljLbh6dI=,tag:5ugom6zd8Y8O8H5cv3uyAg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucmtSK2FJY1Z1NVU4bGhY
        WFBYUFhLNU0xcEloby94dVRzWnh6NFZRcWt3CndJT25wN09jTTVBdGpWdzlaUmJl
        R0M3bGV3Y3BJd0ZLU3VpYXprV2N5cFUKLS0tIEErRU1MZnJxeUhVZTdvVGRFMHVV
        N2FUSDgxbUoydy9ZTFVPOTdoR0szejAKi+RvZGwW0jRqzmhPdRjaBepT9+YmXyFz
        P5ZlpGf3wGH1b7DQEuLOSruV/1NQc1zBthDft9eOFQ7xVaLE6WSe4w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-28T23:57:20Z"
  mac: ENC[AES256_GCM,data:ZibND0jYuhvK1iM2+Fv8A9HEKI4JAZ0Zh3VNVg8Vvam5vN4oTnK0P0lW6bmF89wVPJrXGXgEjKREKcjzQumB1/fPzxuftReaLVL3Hd+yTlcwZSICvIy2+xPcJ7q5aoVn8ax3PkWToo4LWjKgGBOSEdcHbOM8Vu3GU+hfnYrTxF0=,iv:/WdLn1Niu6RwwYEBLA5BkIPfi7geNcuq4in+H1m9lKY=,tag:0F46K2tl8zNcgSAu6oZhlA==,type:str]
  version: 3.13.1
