apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage.yaml
  - configmap.yaml
  - serviceaccount.yaml
  - deployment.yaml
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: hermes
      app.kubernetes.io/component: bot
      app.kubernetes.io/part-of: homelab
      app.kubernetes.io/managed-by: flux
