apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-automerge
  namespace: renovate
spec:
  schedule: "0 8 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: automerge
              # python 3.14-slim
              image: python@sha256:0ba001803c72c128063cfa88863755f905cefabe73c026c66a5a86d8f1d63e98
              command: ["python3", "/scripts/automerge.py"]
              env:
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: secret-renovate-container-env
                      key: RENOVATE_TOKEN
              envFrom:
                - configMapRef:
                    name: renovate-automerge-env
                - secretRef:
                    name: secret-renovate-automerge-env
              volumeMounts:
                - name: script
                  mountPath: /scripts
          volumes:
            - name: script
              configMap:
                name: renovate-automerge-script
          restartPolicy: Never
