apiVersion: v1
kind: Secret
metadata:
    name: secret-renovate-automerge-env
    namespace: renovate
stringData:
    SMTP_USER: ENC[AES256_GCM,data:rlLiDva1JxxAFDIdCuQzZlk=,iv:682upu6YfdPRYDtczzPfIILPYKGt9WX9caMnbicH8Ic=,tag:iOQIT8HP2uaq3uK7NyRuVQ==,type:str]
    SMTP_PASS: ENC[AES256_GCM,data:42R2YUSLb1EpJd5XY+LEwmIvWg==,iv:zzd4FEkMQKjiaOnjGfyyHQKesg+fE9VWrG83/QCcRQk=,tag:HrC7nas8bl86joz+vDmN2A==,type:str]
sops:
    age:
        - recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVUxGMFo1MkZBT2Ztbkc5
            Tm05R0xneGZhb2tYMnlRTnV4QVFoYTU5YnhZCndmelNUY0V1MzJxNzVZN0NNVFoy
            NWJwQWFlK3ZKbDRtYzVKRnh4UzBqa00KLS0tIG1pVW5YNGhRRTQvUUVpWUZDblM3
            Q2gzUVlkc2NOTUdyaXVnWWdCQUFrQVkKfLveOyNJPkd54yAsvsQZt51Xgrvj+92w
            GporjYr+V2zWob/MpneZSb09A7msV/S1LRpmhvy4jBc8br5d76yy2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T16:44:39Z"
    mac: ENC[AES256_GCM,data:Vi1nRW38kRDzc+5mhFKSE5ISo4Zigcp6Xe13piEmWGpqSQ3VSYw9E8GRKsvssmo+lr4KiQRWQqiPIPzd776ImrFz3hLcpKJrpkOvjpXyoA/3DAk35GVFpq8a2Z6Hqj+KLqglZFk9E/rc5zYBgkkrwF1U+hFk0Vl0lUcq3UeFpXw=,iv:lYyuh/F2pDGvnlJwcQgpcRNefveLfPyLoisC1Aaczfw=,tag:eZgcgBlbE+8ZE2u5jjWyKw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
