apiVersion: v1
kind: Secret
metadata:
  name: secret-renovate-automerge-env
  namespace: renovate
stringData:
  SMTP_USER: ENC[AES256_GCM,data:rlLiDva1JxxAFDIdCuQzZlk=,iv:682upu6YfdPRYDtczzPfIILPYKGt9WX9caMnbicH8Ic=,tag:iOQIT8HP2uaq3uK7NyRuVQ==,type:str]
  SMTP_PASS: ENC[AES256_GCM,data:EXTSGAtAftOBGq4kmfq05vrQLAbLB2IVtClTc3nNUw==,iv:uPD+VD2ceDdedlqxyNz493qlCuqvRBLo3HZ50cfxyuI=,tag:cQ36t1CqCaswsfCy7H2ywQ==,type:str]
sops:
  age:
    - recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVUxGMFo1MkZBT2Ztbkc5
        Tm05R0xneGZhb2tYMnlRTnV4QVFoYTU5YnhZCndmelNUY0V1MzJxNzVZN0NNVFoy
        NWJwQWFlK3ZKbDRtYzVKRnh4UzBqa00KLS0tIG1pVW5YNGhRRTQvUUVpWUZDblM3
        Q2gzUVlkc2NOTUdyaXVnWWdCQUFrQVkKfLveOyNJPkd54yAsvsQZt51Xgrvj+92w
        GporjYr+V2zWob/MpneZSb09A7msV/S1LRpmhvy4jBc8br5d76yy2g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-01T18:46:31Z"
  mac: ENC[AES256_GCM,data:CcRDfTyzYRriOhLESO1hH6JF0oe+lKxt4AUnGRPeuL9EU9xdqT3nd9/zuYcNEg/he+bu3E5npEU3SJOgU8trn0Y+6yxr3hDYBLgHJ+I87PMAs2OtfMdl4/Fg/taLP/OFobMh0CtJb76eDewGgH4HLxDF3y+HV9nDFADPmBacM9M=,iv:TjIj7wmywMaKZjzFBtexHP8/K6Z0F1anJLj06KO4IWQ=,tag:Q4ZYvimRWfo1Mium+Z1s7Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
