apiVersion: v1
kind: ConfigMap
metadata:
  name: zigbee2mqtt-env
  namespace: zigbee2mqtt
data:
  ZIGBEE2MQTT_CONFIG_SERIAL_PORT: "tcp://10.42.2.15:6638"
  ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: "ember"
  ZIGBEE2MQTT_CONFIG_MQTT_SERVER: "mqtt://mosquitto.mosquitto"
  ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC: "zigbee2mqtt"
  ZIGBEE2MQTT_CONFIG_HOMEASSISTANT: "true"
  ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: "8080"
