apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  namespace: zigbee2mqtt
  labels:
    app: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      initContainers:
        - name: init-config
          image: busybox@sha256:1487d0af5f52b4ba31c7e465126ee2123fe3f2305d638e7827681e7cf6c83d5e
          command: ['sh', '-c', "if [ ! -s /app/data/configuration.yaml ]; then cp -L /tmp/config/configuration.yaml /app/data/configuration.yaml; fi"]
          volumeMounts:
            - name: config
              mountPath: /tmp/config
            - name: data
              mountPath: /app/data
      containers:
        - name: zigbee2mqtt
          image: koenkk/zigbee2mqtt@sha256:e9279e580bb25c512cf6e54c36e215a5cbd2881d1f201cf2a8213a97b14be3d2
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: zigbee2mqtt-env
          env:
            - name: ZIGBEE2MQTT_DATA
              value: /app/data
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: config
          configMap:
            name: zigbee2mqtt-config
        - name: data
          persistentVolumeClaim:
            claimName: zigbee2mqtt-data-pvc
