apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cadence-site-stage
resources:
  - ../../base/cadence-site/
  - httproute.yaml

labels:
  - pairs:
      env: staging
      app.kubernetes.io/instance: staging
    includeSelectors: false

patches:
  - target:
      kind: Namespace
      name: cadence-site
    patch: |
      - op: replace
        path: /metadata/name
        value: cadence-site-stage
