# AWS credentials for CNPG S3 backups
# Encrypt with SOPS before committing
apiVersion: v1
kind: Secret
metadata:
  name: golinks-aws-creds-secret
  namespace: golinks
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:K4RkHSosY3PbKtB3BkS8/JLIZcM=,iv:qx/XrNWh1gQEE/TcPo5GrJ5t+t1HnN/6BBjkgQNlWYQ=,tag:nGZk3XdiRi90b6CmIze4jA==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:eLnAPGrogwXn5gMrokvUvkDFG+bUI0VntoTQd5DiOifvE9jthbel+w==,iv:mvtqdeWey1ttn1S5DR5Ak1BtPwed8VJa0SHG9jsd6gw=,tag:1NsGkVfVBcQJ7aLLQLk+nA==,type:str]
sops:
  age:
    - recipient: age1lnrpvnhtkmzhfhelxse4798f67l86nct2rjahryvt4rgyfu8zg7samjjuw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cGRZTjNQMy95OEZHaGtW
        YzlGVS8rNDlBYVFoT0RGNE5XYWZIdGEzcjN3CjNKOFlUV3ZCMUorc01lZGx6ZUU5
        Tm5QY1dpcDdZVzNHKzl6S1JSRGlKZkkKLS0tIHNSK0QwR0czM3NKa0tOQVZXcVJ4
        cnZtekhzOStKRklHRWdqbGhwK0lwc2sK7DERlfyszqQtw9QRVZmWQ650hi3HwFye
        Xq5yx6fmAYKHPaibYzSiL9Ve7QT/vZ/rFhCjfl+vSGBABR9Tm/xTdQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T17:08:03Z"
  mac: ENC[AES256_GCM,data:iNtvuxi0oId8Ren7qN8/0zj5XfnnsMLwa+ojEvd1aOZsxQBBM08Q7GwCjAQISQcPNimEmOF0SY8AmRKKzQS9fWBh+mgDh/qXwIqdczoVNo2kxQhfg5/cof4x9xHGqoqqnHRE83lozS5IQkYYgbPDA3v7VMFxRNzNPKutoYMzsrI=,iv:QZGkNvLkkOG2vWc+v0QoZLr2FzrOqiMue+qkjl6kZok=,tag:xTawVYKPGi+KCE55sCXKaw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
