title: BurntBytes Home
description: Production Environment
headerStyle: clean
layout:
  Media:
    style: column
    rows: 10
  Tools:
    style: column
    rows: 10
  Infrastructure:
    style: column
    rows: 10
  Monitoring:
    style: column
    rows: 10
background:
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  blur: sm
  opacity: 30
theme: dark
color: slate
