apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: signal-cli-config
  namespace: signal-cli
  labels:
    app: signal-cli
spec:
  storageClassName: truenas-iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
