apiVersion: batch/v1
kind: Job
metadata:
  name: immich-db-init
  # Flux/Helm hook annotations to ensure it runs during sync/upgrade
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      name: immich-db-init
    spec:
      serviceAccountName: immich
      automountServiceAccountToken: false
      containers:
        - name: db-init
          # postgres 18-alpine
          image: postgres@sha256:22c89fe0d0f507606260237fd55e51f6137f58b2d5bcf6152242b96d9fe8f9a4
          command: ["/bin/sh", "-c"]
          args:
            - echo "Patch me"
          env:
            - name: PGPASSWORD
            - name: PGHOST
      restartPolicy: OnFailure
