apiVersion: batch/v1
kind: Job
metadata:
  name: immich-db-init
  # Flux/Helm hook annotations to ensure it runs during sync/upgrade
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      name: immich-db-init
    spec:
      serviceAccountName: immich
      automountServiceAccountToken: false
      containers:
        - name: db-init
          # postgres 18-alpine
          image: postgres@sha256:54451ecb8ab38c24c3ec123f2fd501303a3a1856a5c66e98cecf2460d5e1e9d7
          command: ["/bin/sh", "-c"]
          args:
            - echo "Patch me"
          env:
            - name: PGPASSWORD
            - name: PGHOST
      restartPolicy: OnFailure
