apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - prometheus-rule.yaml
  - networkpolicy.yaml
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: modemscope
      app.kubernetes.io/component: exporter
      app.kubernetes.io/part-of: homelab
      app.kubernetes.io/managed-by: flux
